# -*- coding: utf-8 -*-
"""4110E012_1004_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OaNMUarOW7zvWsI1tsENGYTzC6DWdeou
"""

x = 1
y = 35656222554887711
z = -3255522

print(type(x))
print(type(y))
print(type(z))