# -*- coding: utf-8 -*-
"""4110E012_1004_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OaNMUarOW7zvWsI1tsENGYTzC6DWdeou
"""

x = 35e3
y = 12E4
z = -87.7e100

print(type(x))
print(type(y))
print(type(z))