# -*- coding: utf-8 -*-
"""4110E012_1004_10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OaNMUarOW7zvWsI1tsENGYTzC6DWdeou
"""

thislist = ["apple", "banana", "cherry"]
print(len(thislist))