# -*- coding: utf-8 -*-
"""4110E012_1004_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OaNMUarOW7zvWsI1tsENGYTzC6DWdeou
"""

x = 1
y = 2.8
z = 1j

print(type(x))
print(type(y))
print(type(z))