# -*- coding: utf-8 -*-
"""4110E012_1004_18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OaNMUarOW7zvWsI1tsENGYTzC6DWdeou
"""

thisdict = {
  "brand": "Ford",
  "electric": False,
  "year": 1964,
  "colors": ["red", "white", "blue"]
}