# -*- coding: utf-8 -*-
"""4110E012_1004_13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OaNMUarOW7zvWsI1tsENGYTzC6DWdeou
"""

mylist = ["apple", "banana", "cherry"]
print(type(mylist))
thislist = list(("apple", "banana", "cherry")) # note the double round-brackets
print(thislist)