# -*- coding: utf-8 -*-
"""4110E012_1004_12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OaNMUarOW7zvWsI1tsENGYTzC6DWdeou
"""

list1 = ["abc", 34, True, 40, "male"]