# -*- coding: utf-8 -*-
"""4110E012_20221011_python_loop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Fnq7kjWDUX5euRmGODoapYZ5a4rhW12
"""

list1=range(10)
print(list1)

print(list(list1))

list2=range(-4,5)
print(list(list2))

list3=range(-4,5,2)
print(list(list3))

list4=range(-4,6,2)
print(list(list4))

for n in range(5):
  print(n)

for n in range(10):
    print(n, end='@')

mysum = 0

for n in range(5):
  mysum += n
  print(mysum)

mysum = 0

for n in range(5):
  mysum += n

print(mysum)

x = int(input("請輸入一個正整數:"))

mysum = 0

for n in range(x+1): ## 為什麼不是range(x)?
  mysum += n

print(mysum)

total = i = 1

n = int(input("請輸入正整數 n 的值："))

while(i<=n):
    total *= i  
    i+=1      

print("%d!=%d" % (n, total))