# -*- coding: utf-8 -*-
"""4110E012_20221011_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Fnq7kjWDUX5euRmGODoapYZ5a4rhW12
"""

a = 33
b = 22
if(a>b):
  print("a>b")
elif(a<b):
  print("a<b")
else:
  print("a=b")