# -*- coding: utf-8 -*-
"""4110E012_1004.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OaNMUarOW7zvWsI1tsENGYTzC6DWdeou
"""

a = int(input("輸入:"))
a

b=a+1
b